### ISSUE TITLE
Serial loop

### ISSUE THREAD

**Issue by Ben0p** [farmstar/farmstar#3]
Requirement to have several instances of serial interfaces logging asynchronously. Currently reading the serial interface in a while true loop and processing gps data on the fly. (Backend scripts).

**Comment by farmstar** [comment]
Or at least in a separate module to call upon so we don't have to have the code in every file for testing. This doesn't work in practice due to the loop.

**Comment by Ben0p** [comment]
Fixed, was just my noob python skills, call a class once to init the variables then loop the function only within the class, not the whole class. Should be able to call the class once for each serial interface then put them in the one loop.
