### ISSUE TITLE
Map rotation

### ISSUE THREAD

**Issue by Ben0p** [farmstar/farmstar#4]
Currently no way to rotate the map to reflect heading. This is a leaflet restriction.

**Comment by MR-L-C** [comment]
var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
	osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
	osm = L.tileLayer(osmUrl, {maxZoom: 18, attribution: osmAttrib});

var map = L.map('map', {rotate: true})
		.setView([55, 10], 4)
		.addLayer(osm);

**Comment by Ben0p** [comment]
That or use mapbox, closing issue
